// packages/ds-core/output/vue/vue3/src/components/button/button.vue
<template>
  <div :class="`button`">
    {{ message || "Hello" }} {{ name }}! I can run in React, Vue, Solid or
    Svelte!
  </div>
</template>

<script>
import { defineComponent } from "vue";

import "./button.scss";

export default defineComponent({
  name: "dse-button",

  props: ["message"],

  data() {
    return { name: "Hello World" };
  },
});
</script>

// packages/ds-core/output/react/src/components/button/button.tsx
"use client";
import * as React from "react";
import { useState } from "react";

type Props = {
  message: string;
  backgroundColor: Color;
};
import { Color } from "typings";
import "./button.scss";

function DSEButton(props: Props) {
  const [name, setName] = useState(() => "Hello World");

  return (
    <div className={`button`}>
      {props.message || "Hello"}
      {name}! I can run in React, Vue, Solid or Svelte!
    </div>
  );
}

export default DSEButton;
