// packages/ds-react/src/components/button/button.tsx
"use client";
import * as React from "react";
import { useState } from "react";

function Button(props: ButtonProps) {
  const [name, setName] = useState(() => "Hello Youth");

  return (
    <div className={`button button-lg`}>
      {props.message || "Hello"}
      {name}! I can run in React, Vue, Solid or
    </div>
  );
}

export default Button;

// packages/ds-core/output/vue/vue3/src/components/button/button.vue
<template>
  <div :class="`button`">
    {{ message || "Hello" }} {{ name }}! I can run in React, Vue, Solid or
    Svelte!
  </div>
</template>

<script>
import { defineComponent } from "vue";

import "./button.scss";

export default defineComponent({
  name: "dse-button",

  props: ["message"],

  data() {
    return { name: "Hello World" };
  },
});
</script>
